INSERT INTO "ZMENU" VALUES(1,4,3,1,2,'toNormal, toFixed, toExponential, toExponential, mode_degrees, mode_radians','STD, FIX, SCI, ENG, DEG, RAD','Mode');
INSERT INTO "ZMENU" VALUES(2,4,3,0,2,'sin, asin, cos, acos, tan, atan, polar_to_cartesian, cartesian_to_polar, real_to_complex, complex_to_real, arg, , unimp, unimp, unimp, unimp, degrees_to_radian, radian_to_degrees','SIN, ASIN, COS, ACOS, TAN, ATAN, P->R, R->P, R->C, C->R, ARG, , ->HMS, HMS->, HMS+, HMS-, D->R, R->D','Trig');
INSERT INTO "ZMENU" VALUES(3,4,3,7,2,'store_eq, recall_eq, var_for_eq, draw','STEQ, RCEQ, INDEP, DRAW','Plot');
INSERT INTO "ZMENU" VALUES(4,4,2,2,2,'@display_dec, @display_hex, @display_hex, @display_bin, @display_store_ws, @display_recall_ws, bin_rotate_left, bin_rotate_right, bin_rotate_left_byte, bin_rotate_right_byte, real_to_binary, binary_to_real, bin_shift_left, bin_shift_right, bin_shift_left_byte, bin_shift_right_byte, arithmetic_shift_right, , bin_and, bin_or, bin_xor, bin_not','DEC, HEX, OCT, BIN, STWS, RCWS, RL, RR, RLB, RRB, R->B, B->R, SL, SR, SLB, SRB, ASR, , AND, OR, XOR, NOT','Binary');
INSERT INTO "ZMENU" VALUES(5,4,7,4,2,'negate, fact, random, rand_seed, real_max, real_min, abs, sign, mantissa, exponent, , , int, fract, floor, ceil, round, , max, min, %, percent_of_total','NEG, FACT, RAND, RDZ, MAXR, MINR, ABS, SIGN, MANT, XPON, , , IP, FP, FLOOR, CEIL, RND, , MAX, MIN, MOD, %T','Real');
INSERT INTO "ZMENU" VALUES(6,4,3,6,2,'store_eq, recall_eq, @solver, @isolator, solve_quad, solve_show, solve_for_root','STEQ, RCEQ, SOLVR, ISOL, QUAD, SHOW, ROOT','Solve');
INSERT INTO "ZMENU" VALUES(7,4,2,3,2,'log, alog, ln, exp, ln_plus_one, exp_minus_one, sinh, asinh, cosh, acosh, tanh, atanh','LOG, ALOG, LN, EXP, LNP1, EXPM, SINH, ASINH, COSH, ACOSH, TANH, ATANH','Logs');
INSERT INTO "ZMENU" VALUES(8,4,2,5,2,'into_array, from_array','->ARRY, ARRY->','Array');
INSERT INTO "ZMENU" VALUES(9,4,3,8,2,'stat_add, stat_del_last, stat_count, stat_clear, stat_store, stat_recall, stat_total, stat_mean, stat_standard_deviation, stat_variance, stat_max_val, stat_min_val, stat_select_col, stat_correlation, stat_covariance, stat_linear_regression, stat_predictive_val','∑+, ∑-, N∑, CL∑, STO∑, RCL∑, TOT, MEAN, SDEV, VAR, MAX∑, MIN∑, COL∑, CORR, COV, LR, PREDV','Stat');
